CREATE TABLE USER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    LOGIN VARCHAR(255),
    PASSWORD VARCHAR(255),
    SALT VARCHAR(255),
    CONSTRAINT UQ_LOGIN UNIQUE(LOGIN)
);

CREATE TABLE ROLE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    RESOURCE VARCHAR(255),
    USER_ID INT,
    constraint FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE ACCOUNTING(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VOLUME INT,
    DATE_START DATE,
    DATE_END DATE,
    ROLE_ID INT,
    constraint FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);